version: '3.8'
services:
  frontend:
    build:
      context: ../slarra
      dockerfile: Dockerfile
    volumes:
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    volumes:
      - backend_node_modules:/app/node_modules
    ports:
      - "8001:8001"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  frontend_node_modules:
  backend_node_modules:
  mongo_data:
